swagger: "2.0"
info:
  title: Department API Documentation
  description: Department API Documentation
  version: 1.0.0
paths:
  /apartment:
    get:
      tags:
        - Department
      summary: 'Get list Department'
      description: 'Get list Department'
      produces:
        - application/json
      responses:
        '200':
          description: A list of pets.
          schema:
            type: object
            properties:
              is_success:
                type: boolean
                example: true
              message:
                type: string
                example: ''
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Department'
  /login:
    post:
      tags:
        - Login
      summary: 'Login'
      description: 'Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login.
          schema:
            type: object
            properties:
              is_success:
                type: boolean
                example: true
              message:
                type: string
                example: 'Login successfully'
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Login'
  /register:
    post:
      tags:
        - Register
      summary: 'Register'
      description: 'Register new account'
      produces:
        - application/json
      responses:
        '200':
          description: Register new account'.
          schema:
            type: object
            properties:
              is_success:
                type: boolean
                example: true
              message:
                type: string
                example: 'User Registered'
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Register'
  /logout:
    post:
      tags:
        - Logout
      summary: 'Logout'
      description: 'Logout'
      produces:
        - application/json
      responses:
        '200':
          description: Logout'.
          schema:
            type: object
            properties:
              is_success:
                type: boolean
                example: true
              message:
                type: string
                example: 'Logged out'

components:
  schemas:
    Department:
      type: object
      properties:
        no_department:
         type: string
         example: "DPM59"
        type_department:
         type: number
         example: 1
        status:
          type: number
          example: 1
        description:
          type: number
          example: 1
        square_meters:
          type: number
          example: 1
      xml:
        name: Department
    Login:
      type: object
      properties:
        user:
         type: object
         properties:
          id:
            type: string
            example: 10
          user_name:
            type: string
            example: "ty4"
          email:
            type: string
            example: "ty4@gmail.com"
          name:
            type: string
            example: "123456"
          dob:
            type: date
            example: "2000-12-31"
          department_id:
            type: number
            example: 1
          phone:
            type: string
            example: "0987654321"
          role:
            type: number
            example: 1
          avatar:
            type: string
            example: "https://img.freepik.com/free-photo/hand-painted-watercolor-background-with-sky-clouds-shape_24972-1095.jpg?size=626&ext=jpg"
          created_at:
            type: datetime
            example: "2022-01-20T06:03:10.000000Z"
          updated_at:
            type: datetime
            example: "2022-01-20T06:03:10.000000Z"
        token:
         type: string
         example: "1|tsRmBoNrTbBE2Z1m9fJTdd6K1O6wY1IfJ8RTFSbd"
      xml:
        name: Login
    Register:
      type: object
      properties:
        token:
         type: string
         example: "7|OZ6J1PNvifzScSlKCCOXL743AF0mSxOEjkTfyVZo"
        user:
         type: object
         properties:
          user_name:
            type: string
            example: "ty5"
          email:
            type: string
            example: "ty5@gmail.com"
          name:
            type: string
            example: "Duc Anh"
          department_id:
            type: number
            example: 1
          role:
            type: number
            example: 1
          created_at:
            type: datetime
            example: "2022-01-20T06:03:10.000000Z"
          updated_at:
            type: datetime
            example: "2022-01-20T06:03:10.000000Z"
      xml:
        name: Register